#!/usr/bin/env python
# vim:ft=python

# Average over files specified in argument
# Assumes first 'n' (default=1) columns are keys

import sys
import numpy as np

def read_from_files(files):
    # Store for the files

    values = []
    for f in files:
        if f == "-":
            f = sys.stdin
        else:
            f = open( f )
        for line in f.xreadlines():
            if line.startswith("#"): continue
            values.append( np.array( map( float, line.split() ) ) )

    return np.array( values )

def plot_scatter( values, bins = 10, out = None ):
    import matplotlib.pyplot as plt
    N, spec, dspec, spem, dspem, em, dem = values.T
    plt.rc('text', usetex=True)
    plt.rc('font', family="serif")
    plt.xlabel("n")
    plt.xscale("log")
    plt.errorbar( N, spec, yerr=0.1*dspec, label = "Spectral", fmt='o--', linewidth=2.5 )
    plt.errorbar( N, spem, yerr=0.1*dspem, label = "Spectral+EM", fmt='o-', linewidth=2.5 )
    plt.errorbar( N, em, yerr=0.1*dem, label = "EM", fmt='o:', linewidth=2.5 )
    plt.xlim((5e2,1e7))
    plt.ylabel(r"\|\theta^* - \hat\theta\|_F", fontsize=24)
    plt.xlabel("n", fontsize=24)

    plt.legend()
    #if out is not None:
    #plt.savefig( "1833-decay.png" )
    plt.savefig( "1833-rm-decay.pdf" )
    #plt.show()

def main(*args):
    if len(args) == 0 or args[0] == "-h":
        print "Usage scatter [-h] <list-of-files>" 
        sys.exit(1)

    if args[0] == "-bins" or args[0] == "-b" :
        bins = int( args[1] )
        files = args[2:]
    else:
        bins = 10
        files = args

    values = read_from_files( files )
    plot_scatter( values )


if __name__ == "__main__":
    main(*sys.argv[1:])

