#!/usr/bin/env python
# vim:ft=python

# Average over files specified in argument
# Assumes first 'n' (default=1) columns are keys

import sys
import numpy as np

def read_from_files(files):
    # Store for the files

    values = []
    for f in files:
        if f == "-":
            f = sys.stdin
        else:
            f = open( f )
        for line in f.xreadlines():
            if( line.startswith('#') ): 
                continue
            values.append( np.array( map( float, line.split() ) ) )

    return np.array( values )

def plot_hist( values, out = None ):
    import matplotlib.pyplot as plt

    labels = ["EM", "Spectral", "Spectral + EM"]
    pos = np.array( range(len(labels)) ) + 0.5

    i = 0
    for vals in values[0]:
        plt.clf()
        plt.rc('font', size=20)

        vals = [[vals[0], vals[1]], 
              [vals[2], vals[3]], 
              [vals[4], vals[5]]]

        plt.ylabel("Parameter Error")
        plt.ylim((0,3))
        colors = ["red", "green", "blue"]
        hatches = ["/", ".", "*"]
        lst = zip(pos, vals, labels, hatches, colors)
        lst.reverse()
        for (po, (v,e), label, hatch, color) in lst:
            plt.bar( po, v, yerr=e, label=label, hatch=hatch, color=color, alpha=0.9 )
        plt.xticks( pos + 0.25, labels )

        #ax = plt.gca()
        #ax.invert_yaxis()

        #plt.legend()
        plt.savefig( "err-hist-%d.pdf"%i, transparent=True )
        #plt.savefig( "hist-spec.pdf" )
        #plt.savefig( "hist-spem.pdf" )
        #plt.show()
        #plt.savefig( "hist.pdf" )
        i+=1

def main(*args):
    if len(args) == 0 or args[0] == "-h":
        print "Usage avrg [-h] [-bins x] <list-of-files>" 
        sys.exit(1)

    if args[0] == "-bins" or args[0] == "-b" :
        bins = int( args[1] )
        files = args[2:]
    else:
        bins = 10
        files = args

    values = [ read_from_files( [f] ) for f in files ]
    plot_hist( values, bins )


if __name__ == "__main__":
    main(*sys.argv[1:])

